[workspace]
channels = ["conda-forge"]
name = "prefect3 test"
platforms = ["linux-64", "osx-64", "osx-arm64"]

[dependencies]
prefect = ">=3.4.12"
tiled-client = ">0.1.b036"
python = "<3.13"
databroker = "*"
xraylib = "*"
scikit-beam = "*"
black = ">=25.1.0,<26"

[pypi-dependencies]
pyxrf = { git = "https://github.com/NSLS2/pyxrf.git", rev="7b7d868" }
